SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE enrollments;
TRUNCATE TABLE order_items;
TRUNCATE TABLE orders;
TRUNCATE TABLE cart_items;
TRUNCATE TABLE coupons;
TRUNCATE TABLE posts;
TRUNCATE TABLE courses;
TRUNCATE TABLE categories;
TRUNCATE TABLE instructors;
TRUNCATE TABLE users;
TRUNCATE TABLE roles;

SET FOREIGN_KEY_CHECKS = 1;

-- Roles y usuarios demo
INSERT INTO roles (name, description) VALUES
('admin', 'Administrador del sistema'),
('editor', 'Editor de cursos y contenidos'),
('client', 'Cliente que puede comprar cursos'),
('guest', 'Visitante sin compras');

-- Contraseña demo para los 4 usuarios: password
INSERT INTO users (id, name, email, password, role) VALUES
(1, 'Admin CoderUp', 'admin@coderup.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/iWslm.1.6.m5YGOvq', 'admin'),
(2, 'Editor CoderUp', 'editor@coderup.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/iWslm.1.6.m5YGOvq', 'editor'),
(3, 'Cliente CoderUp', 'cliente@coderup.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/iWslm.1.6.m5YGOvq', 'client'),
(4, 'Guest CoderUp', 'guest@coderup.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/iWslm.1.6.m5YGOvq', 'guest');

-- Instructores
INSERT INTO instructors (id, name, email, bio, avatar_url, specialty, years_experience, total_students, rating) VALUES
(1, 'Juan García López', 'juan@coderup.com', 'Experto en React y JavaScript moderno. 5 años en desarrollo frontend. Ha mentorizado a más de 2400 estudiantes. Apasionado por la arquitectura de componentes escalable, accesibilidad y rendimiento web.', '/instructors/juan-garcia.jpeg', 'React / Frontend', 5, 2400, 4.80),
(2, 'María López Rodríguez', 'maria@coderup.com', 'Especialista en backend con Node.js, PHP y bases de datos. 6 años en arquitectura de sistemas. Diseña APIs que sirven a millones de requests y acompaña a equipos en decisiones técnicas defendibles.', '/instructors/maria-lopez.png', 'Node.js / Backend', 6, 3100, 4.90),
(3, 'Carlos Rodríguez Pérez', 'carlos@coderup.com', 'DevOps engineer con experiencia en Docker, Kubernetes y AWS. 7 años en infraestructura. Ha desplegado sistemas críticos en producción y domina CI/CD, observabilidad y automatización.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&h=400&q=82', 'DevOps / Infraestructura', 7, 1800, 4.70),
(4, 'Ana Martínez García', 'ana@coderup.com', 'Diseñadora UI/UX con pasión por la experiencia de usuario. 4 años en diseño digital. Ha trabajado con startups y grandes empresas, con foco en accesibilidad y sistemas visuales.', '/instructors/ana-martinez.png', 'Diseño UI/UX', 4, 900, 4.60);

-- Categorías del catálogo
INSERT INTO categories (id, name, slug, description, icon) VALUES
(1, 'Frontend', 'frontend', 'HTML, CSS, JavaScript, React, Vue, Angular', 'code'),
(2, 'Backend', 'backend', 'Node.js, PHP, Python, APIs REST, bases de datos', 'hexagon'),
(3, 'DevOps', 'devops', 'Docker, Kubernetes, CI/CD, infraestructura', 'container'),
(4, 'Mobile', 'mobile', 'React Native, Flutter y desarrollo móvil', 'smartphone'),
(5, 'Diseño', 'diseno', 'Diseño UI/UX, Figma y accesibilidad', 'palette'),
(6, 'IA', 'ia', 'Inteligencia artificial aplicada, automatización y machine learning', 'brain-circuit'),
(7, 'Ciberseguridad', 'ciberseguridad', 'Seguridad web, auditoría, protección de datos y hardening', 'shield-check');

-- Cursos publicados
INSERT INTO courses (id, title, slug, description, thumbnail_url, price, level, category_id, instructor_id, duration_hours, total_lessons, total_students, rating, `requires`, what_you_learn, curriculum, is_published) VALUES
(1, 'React Avanzado', 'react-avanzado', 'Domina React al nivel profesional con hooks personalizados, context API, optimización de rendimiento y patrones de arquitectura escalable. Incluye proyectos reales para portfolio y criterios para defender decisiones frontend en entornos profesionales.', 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=1200&q=82', 49.99, 'Avanzado', 1, 1, 32, 48, 2400, 4.80, JSON_ARRAY('JavaScript ES6+', 'HTML y CSS', 'Conocimiento básico de React'), JSON_ARRAY('Hooks personalizados', 'Context API y useReducer', 'Optimización con memo', 'Testing con React Testing Library', 'TypeScript en React', 'Routing avanzado', 'State management', 'Componentes escalables'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Hooks Avanzados', 'lecciones', JSON_ARRAY('Custom Hooks', 'useReducer', 'useContext')), JSON_OBJECT('nombre', 'Optimización', 'lecciones', JSON_ARRAY('Code splitting', 'React.memo', 'Profiling')), JSON_OBJECT('nombre', 'Proyecto final', 'lecciones', JSON_ARRAY('E-commerce', 'Dashboard', 'Deploy')))), TRUE),
(2, 'Node.js & APIs REST', 'nodejs-apis-rest', 'Crea APIs robustas con autenticación, validación de datos, conexión a MySQL y patrones RESTful. Aprenderás middleware, error handling, paginación, seguridad y despliegue en producción.', 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=82', 39.99, 'Intermedio', 2, 2, 28, 42, 3100, 4.90, JSON_ARRAY('JavaScript fundamentals', 'npm y Node.js básico', 'HTTP y REST'), JSON_ARRAY('Routing y middleware', 'Autenticación con JWT', 'Validación de entrada', 'MySQL con transacciones', 'Manejo de errores', 'Testing de APIs', 'Deploy cloud', 'Documentación'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Express Fundamentals', 'lecciones', JSON_ARRAY('Setup', 'Routing', 'Middleware')), JSON_OBJECT('nombre', 'Autenticación', 'lecciones', JSON_ARRAY('Hashing', 'Tokens', 'Roles')), JSON_OBJECT('nombre', 'Deployment', 'lecciones', JSON_ARRAY('Railway', 'Variables', 'Logs')))), TRUE),
(3, 'TypeScript Profesional', 'typescript-profesional', 'Lleva TypeScript al siguiente nivel con tipos avanzados, generics, utility types y modelado de estados. Ideal para proyectos grandes con contratos claros entre frontend y backend.', 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=1200&q=82', 44.99, 'Intermedio', 1, 1, 24, 36, 1800, 4.70, JSON_ARRAY('JavaScript ES6+', 'TypeScript básico'), JSON_ARRAY('Tipos avanzados', 'Generics', 'Utility types', 'Type guards', 'DTOs de API', 'Modelado de dominio', 'Refactor seguro', 'Tipado de React'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Tipos Avanzados', 'lecciones', JSON_ARRAY('Union', 'Intersection', 'Narrowing')), JSON_OBJECT('nombre', 'Generics', 'lecciones', JSON_ARRAY('Funciones', 'Constraints', 'Componentes')), JSON_OBJECT('nombre', 'APIs', 'lecciones', JSON_ARRAY('DTO', 'Mappers', 'Errores')))), TRUE),
(4, 'Astro desde Cero', 'astro-desde-cero', 'Crea sitios ultra rápidos con Astro, islands architecture, rutas estáticas, contenido dinámico y despliegue en Vercel. Perfecto para blogs, documentación y plataformas de cursos.', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=82', 34.99, 'Desde cero', 1, 1, 20, 32, 1600, 4.70, JSON_ARRAY('HTML, CSS, JavaScript', 'Node.js básico'), JSON_ARRAY('Astro setup', 'Islands architecture', 'SSG y SSR', 'Layouts', 'Rutas dinámicas', 'SEO', 'Performance', 'Deploy'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Fundamentos', 'lecciones', JSON_ARRAY('Setup', 'Pages', 'Layouts')), JSON_OBJECT('nombre', 'Contenido', 'lecciones', JSON_ARRAY('Markdown', 'Colecciones', 'SEO')), JSON_OBJECT('nombre', 'Deploy', 'lecciones', JSON_ARRAY('Vercel', 'Build', 'Variables')))), TRUE),
(5, 'Python Fullstack', 'python-fullstack', 'Django y FastAPI para desarrollo web completo con Python. Diseña modelos, APIs, autenticación y despliegues preparados para proyectos escalables.', 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&w=1200&q=82', 54.99, 'Intermedio', 2, 2, 40, 52, 2100, 4.80, JSON_ARRAY('Python fundamentals', 'SQL básico'), JSON_ARRAY('Django ORM', 'FastAPI', 'Autenticación', 'Validación', 'Testing', 'Deploy', 'Plantillas', 'Optimización'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Django', 'lecciones', JSON_ARRAY('Models', 'Views', 'Admin')), JSON_OBJECT('nombre', 'FastAPI', 'lecciones', JSON_ARRAY('Routes', 'Pydantic', 'Docs')), JSON_OBJECT('nombre', 'Producción', 'lecciones', JSON_ARRAY('Gunicorn', 'Docker', 'Logs')))), TRUE),
(6, 'Docker & Kubernetes', 'docker-kubernetes', 'Domina containerización y orquestación con Docker, docker-compose, Kubernetes, servicios y despliegue cloud. Esencial para DevOps y equipos modernos.', 'https://images.unsplash.com/photo-1605745341112-85968b19335b?auto=format&fit=crop&w=1200&q=82', 59.99, 'Avanzado', 3, 3, 36, 48, 1800, 4.70, JSON_ARRAY('Linux básico', 'Networking', 'Git'), JSON_ARRAY('Dockerfiles', 'Images y containers', 'Compose', 'Kubernetes pods', 'Services', 'Deployments', 'CI/CD', 'Monitoring'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Docker', 'lecciones', JSON_ARRAY('Images', 'Containers', 'Volumes')), JSON_OBJECT('nombre', 'Kubernetes', 'lecciones', JSON_ARRAY('Pods', 'Services', 'ConfigMaps')), JSON_OBJECT('nombre', 'Cloud', 'lecciones', JSON_ARRAY('Registry', 'Deploy', 'Logs')))), TRUE),
(7, 'Tailwind CSS Masterclass', 'tailwind-css-masterclass', 'Crea interfaces profesionales con Tailwind CSS, responsive design, dark mode, animaciones y sistemas de componentes mantenibles.', 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?auto=format&fit=crop&w=1200&q=82', 24.99, 'Intermedio', 1, 4, 16, 28, 900, 4.60, JSON_ARRAY('HTML y CSS', 'Responsive design'), JSON_ARRAY('Utility-first', 'Responsive', 'Dark mode', 'Animaciones', 'Config custom', 'Componentes', 'Accesibilidad', 'Performance'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Fundamentos', 'lecciones', JSON_ARRAY('Utilities', 'Responsive', 'States')), JSON_OBJECT('nombre', 'Sistema visual', 'lecciones', JSON_ARRAY('Theme', 'Plugins', 'Dark mode')), JSON_OBJECT('nombre', 'Proyectos', 'lecciones', JSON_ARRAY('Landing', 'Dashboard', 'Ecommerce')))), TRUE),
(8, 'Git & GitHub Pro', 'git-github-pro', 'Control de versiones profesional con ramas, pull requests, resolución de conflictos, GitHub Actions y workflows de equipo.', 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?auto=format&fit=crop&w=1200&q=82', 19.99, 'Desde cero', 3, 3, 14, 24, 1200, 4.70, JSON_ARRAY('Terminal básica'), JSON_ARRAY('Commits claros', 'Branching', 'Merge conflicts', 'Pull requests', 'Code review', 'Actions', 'Git flow', 'Releases'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Git básico', 'lecciones', JSON_ARRAY('Init', 'Add', 'Commit')), JSON_OBJECT('nombre', 'Colaboración', 'lecciones', JSON_ARRAY('Branches', 'PRs', 'Reviews')), JSON_OBJECT('nombre', 'CI/CD', 'lecciones', JSON_ARRAY('Actions', 'Checks', 'Deploy')))), TRUE),
(9, 'SQL & Bases de Datos', 'sql-bases-de-datos', 'MySQL y PostgreSQL desde diseño relacional hasta queries avanzadas, índices, transacciones y optimización.', 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=1200&q=82', 29.99, 'Desde cero', 2, 2, 24, 36, 3100, 4.90, JSON_ARRAY('Conceptos de tablas', 'Relaciones'), JSON_ARRAY('SELECT', 'JOINs', 'Subqueries', 'Transacciones', 'Índices', 'EXPLAIN', 'Normalización', 'Backups'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Consultas', 'lecciones', JSON_ARRAY('SELECT', 'WHERE', 'ORDER')), JSON_OBJECT('nombre', 'Relaciones', 'lecciones', JSON_ARRAY('JOIN', 'FK', '3NF')), JSON_OBJECT('nombre', 'Performance', 'lecciones', JSON_ARRAY('Indexes', 'EXPLAIN', 'Locks')))), TRUE),
(10, 'HTML & CSS desde Cero', 'html-css-desde-cero', 'Fundamentos del desarrollo web con HTML5 semántico, CSS moderno, flexbox, grid, responsive design y accesibilidad.', 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1200&q=82', 0.00, 'Desde cero', 1, 4, 18, 30, 900, 4.60, JSON_ARRAY('Ninguno'), JSON_ARRAY('HTML semántico', 'CSS base', 'Flexbox', 'Grid', 'Responsive', 'Formularios', 'Accesibilidad', 'Publicación'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'HTML', 'lecciones', JSON_ARRAY('Tags', 'Forms', 'Semantics')), JSON_OBJECT('nombre', 'CSS', 'lecciones', JSON_ARRAY('Box model', 'Flexbox', 'Grid')), JSON_OBJECT('nombre', 'Proyecto', 'lecciones', JSON_ARRAY('Portfolio', 'Landing', 'Responsive')))), TRUE),
(11, 'React Native Apps', 'react-native-apps', 'Desarrolla apps iOS y Android con React Native y Expo. Incluye navegación, almacenamiento, permisos, rendimiento y publicación.', 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1200&q=82', 49.99, 'Intermedio', 4, 1, 32, 44, 2400, 4.80, JSON_ARRAY('React fundamentals', 'JavaScript ES6+'), JSON_ARRAY('Expo setup', 'Navegación', 'State management', 'Camera', 'Location', 'Storage', 'Performance', 'Publicación'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Expo', 'lecciones', JSON_ARRAY('Setup', 'Components', 'Styles')), JSON_OBJECT('nombre', 'Features', 'lecciones', JSON_ARRAY('Permissions', 'Camera', 'Location')), JSON_OBJECT('nombre', 'Stores', 'lecciones', JSON_ARRAY('TestFlight', 'Play Store', 'Builds')))), TRUE),
(12, 'UI/UX Design Fundamentals', 'ui-ux-design-fundamentals', 'Principios de diseño, investigación de usuarios, prototipado, Figma, accesibilidad y sistemas visuales aplicados a productos digitales.', 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1200&q=82', 39.99, 'Desde cero', 5, 4, 26, 38, 900, 4.60, JSON_ARRAY('Curiosidad por producto', 'Navegador'), JSON_ARRAY('Design thinking', 'Color', 'Tipografía', 'Wireframes', 'Prototipos', 'Figma', 'Accesibilidad', 'Case study'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'UX', 'lecciones', JSON_ARRAY('Research', 'Personas', 'Flows')), JSON_OBJECT('nombre', 'UI', 'lecciones', JSON_ARRAY('Color', 'Typography', 'Components')), JSON_OBJECT('nombre', 'Figma', 'lecciones', JSON_ARRAY('Auto layout', 'Prototype', 'Handoff')))), TRUE),
(13, 'Inteligencia Artificial para Developers', 'inteligencia-artificial-developers', 'Aprende a integrar IA generativa en aplicaciones reales: prompts, embeddings, asistentes, automatización y evaluación de respuestas. Un curso práctico para crear funciones útiles, medibles y seguras.', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=82', 64.99, 'Intermedio', 6, 2, 30, 44, 1450, 4.80, JSON_ARRAY('JavaScript o Python básico', 'HTTP y APIs'), JSON_ARRAY('Prompts robustos', 'Embeddings', 'Asistentes con contexto', 'Automatización', 'Evaluación de respuestas', 'Costes y límites', 'Privacidad', 'Deploy'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Fundamentos de IA aplicada', 'lecciones', JSON_ARRAY('Modelos', 'Prompts', 'Tokens')), JSON_OBJECT('nombre', 'Integración en producto', 'lecciones', JSON_ARRAY('APIs', 'Embeddings', 'RAG básico')), JSON_OBJECT('nombre', 'Proyecto final', 'lecciones', JSON_ARRAY('Asistente de estudio', 'Evaluación', 'Deploy')))), TRUE),
(14, 'Ciberseguridad Web Esencial', 'ciberseguridad-web-esencial', 'Protege aplicaciones web con fundamentos de seguridad, OWASP Top 10, validación, autenticación, control de sesiones y buenas prácticas para despliegues más seguros.', 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=82', 54.99, 'Intermedio', 7, 3, 28, 40, 980, 4.70, JSON_ARRAY('HTML y JavaScript básico', 'Conceptos de backend'), JSON_ARRAY('OWASP Top 10', 'Validación segura', 'Autenticación', 'Control de sesiones', 'Protección de APIs', 'Headers de seguridad', 'Logs', 'Checklist de despliegue'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Amenazas comunes', 'lecciones', JSON_ARRAY('XSS', 'SQL Injection', 'CSRF')), JSON_OBJECT('nombre', 'Defensa en backend', 'lecciones', JSON_ARRAY('Validación', 'Tokens', 'Permisos')), JSON_OBJECT('nombre', 'Auditoría básica', 'lecciones', JSON_ARRAY('Headers', 'Logs', 'Checklist')))), TRUE),
(15, 'Machine Learning con Python', 'machine-learning-python', 'Construye modelos de machine learning desde cero con Python, pandas, scikit-learn y métricas de evaluación. Ideal para entender datos antes de llevar IA a producción.', 'https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=1200&q=82', 59.99, 'Intermedio', 6, 2, 34, 46, 1320, 4.80, JSON_ARRAY('Python básico', 'Álgebra básica'), JSON_ARRAY('Limpieza de datos', 'Pandas', 'Modelos supervisados', 'Validación', 'Métricas', 'Pipelines', 'Visualización', 'Proyecto predictivo'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Datos', 'lecciones', JSON_ARRAY('CSV', 'Pandas', 'Limpieza')), JSON_OBJECT('nombre', 'Modelos', 'lecciones', JSON_ARRAY('Regresión', 'Clasificación', 'Métricas')), JSON_OBJECT('nombre', 'Proyecto', 'lecciones', JSON_ARRAY('Dataset real', 'Entrenamiento', 'Informe')))), TRUE),
(16, 'Testing Frontend Profesional', 'testing-frontend-profesional', 'Asegura interfaces con Vitest, React Testing Library, mocks, pruebas de accesibilidad y criterios de calidad antes del despliegue.', 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=82', 44.99, 'Intermedio', 1, 1, 22, 34, 870, 4.70, JSON_ARRAY('JavaScript', 'React básico'), JSON_ARRAY('Tests unitarios', 'Testing Library', 'Mocks', 'Accesibilidad', 'Cobertura útil', 'CI', 'Refactor seguro', 'Debug de fallos'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Fundamentos', 'lecciones', JSON_ARRAY('Arrange Act Assert', 'Vitest', 'Matchers')), JSON_OBJECT('nombre', 'Componentes', 'lecciones', JSON_ARRAY('Queries', 'Eventos', 'Mocks')), JSON_OBJECT('nombre', 'Calidad continua', 'lecciones', JSON_ARRAY('Coverage', 'CI', 'A11y')))), TRUE),
(17, 'Laravel y PHP Moderno', 'laravel-php-moderno', 'Desarrolla aplicaciones backend con Laravel, Eloquent, migraciones, validación, autenticación y APIs listas para conectar con frontends modernos.', 'https://images.unsplash.com/photo-1599507593499-a3f7d7d97667?auto=format&fit=crop&w=1200&q=82', 49.99, 'Intermedio', 2, 2, 32, 42, 1180, 4.70, JSON_ARRAY('PHP básico', 'SQL básico'), JSON_ARRAY('Rutas y controladores', 'Eloquent ORM', 'Migraciones', 'Validación', 'Autenticación', 'APIs JSON', 'Testing', 'Deploy'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Laravel base', 'lecciones', JSON_ARRAY('Instalación', 'Rutas', 'Controladores')), JSON_OBJECT('nombre', 'Datos', 'lecciones', JSON_ARRAY('Migraciones', 'Modelos', 'Relaciones')), JSON_OBJECT('nombre', 'API', 'lecciones', JSON_ARRAY('Resources', 'Auth', 'Deploy')))), TRUE),
(18, 'Automatización con GitHub Actions', 'automatizacion-github-actions', 'Crea pipelines de CI/CD para builds, tests, análisis de calidad y despliegues automáticos con workflows claros y mantenibles.', 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?auto=format&fit=crop&w=1200&q=82', 34.99, 'Intermedio', 3, 3, 18, 30, 760, 4.60, JSON_ARRAY('Git básico', 'npm o Composer'), JSON_ARRAY('Workflows YAML', 'Jobs y steps', 'Secrets', 'Build automático', 'Tests en CI', 'Deploy', 'Badges', 'Buenas prácticas'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'CI base', 'lecciones', JSON_ARRAY('Workflow', 'Jobs', 'Cache')), JSON_OBJECT('nombre', 'Calidad', 'lecciones', JSON_ARRAY('Tests', 'Lint', 'Artifacts')), JSON_OBJECT('nombre', 'Deploy', 'lecciones', JSON_ARRAY('Secrets', 'Environments', 'Rollback')))), TRUE);

-- Blog
INSERT INTO posts (title, slug, excerpt, content, cover_image_url, author_id, category, tags, read_time_minutes, is_published, published_at) VALUES
('Guía práctica de Hooks en React', 'guia-completa-hooks-react', 'Aprende cuándo usar useState, useEffect, useContext y custom hooks con ejemplos pensados para una plataforma de cursos.', '<h2>Por qué importan los hooks</h2><p>Los hooks permiten crear pantallas interactivas sin convertir cada componente en una estructura difícil de seguir. En CoderUp se usan para controlar formularios, filtros de cursos, carrito, autenticación y carga de datos desde la API.</p><p>useState ayuda con estados cercanos a la interfaz, como abrir un modal o recordar una búsqueda. useEffect sirve para sincronizar la pantalla con datos externos, por ejemplo al pedir cursos a MySQL. useContext es útil cuando una información debe compartirse entre varias zonas, como el usuario autenticado o el carrito.</p><h2>Buenas prácticas para clientes</h2><p>Un buen hook debe resolver una responsabilidad concreta y devolver nombres fáciles de entender. Esto mejora la accesibilidad del producto porque los estados de carga, error y éxito se muestran de forma clara, sin dejar al cliente esperando sin explicación.</p><p>También conviene cuidar las dependencias de useEffect. Si están mal definidas, la página puede repetir peticiones o enseñar datos desactualizados. Separar la lógica en hooks pequeños hace que el comportamiento sea más previsible y fácil de mantener.</p><h2>Conclusión</h2><p>Dominar hooks no consiste en memorizar funciones, sino en construir experiencias fluidas, comprensibles y preparadas para crecer.</p>', 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=1200&q=82', 1, 'React', JSON_ARRAY('react', 'hooks', 'javascript'), 8, TRUE, NOW()),
('TypeScript vs JavaScript: cuál elegir', 'typescript-vs-javascript', 'Compara ambas opciones desde un punto de vista práctico: velocidad, seguridad, mantenimiento y trabajo con APIs.', '<h2>La diferencia en el día a día</h2><p>JavaScript permite empezar rápido y sigue siendo la base del desarrollo web moderno. TypeScript añade tipos encima de JavaScript para detectar errores antes del despliegue y documentar mejor cómo se usan los datos.</p><p>En una plataforma e-learning aparecen entidades como cursos, instructores, usuarios, pedidos y cupones. Si esos datos están tipados, el equipo sabe qué campos existen, qué valores son opcionales y qué errores debe manejar cada pantalla.</p><h2>Cuándo merece la pena</h2><p>TypeScript compensa especialmente cuando hay formularios, roles, carrito, panel de administración y comunicación con backend. El editor guía al programador y ayuda a evitar fallos visibles para el cliente, como precios mal formateados o cursos sin imagen.</p><p>No hace falta escribir tipos complejos desde el primer día. La estrategia más sana es empezar por las respuestas de API, las props de componentes y los estados críticos. Después se amplía donde aporte claridad real.</p><h2>Conclusión</h2><p>Para proyectos que van a crecer, TypeScript mejora la confianza técnica y hace que el mantenimiento sea más ordenado.</p>', 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=1200&q=82', 1, 'TypeScript', JSON_ARRAY('typescript', 'javascript', 'tipos'), 7, TRUE, NOW()),
('CSS Grid para páginas limpias y responsive', 'css-grid-guia-definitiva', 'Una guía sencilla para crear catálogos, dashboards y layouts adaptables sin depender de estructuras frágiles.', '<h2>Un layout que se entiende</h2><p>CSS Grid permite organizar filas y columnas al mismo tiempo. Esto resulta ideal para catálogos de cursos, listados de blog, paneles de administración y páginas donde el contenido necesita respirar sin perder orden.</p><p>En móvil, una grilla puede mostrarse en una sola columna. En escritorio, esa misma estructura puede convertirse en dos o tres columnas manteniendo el HTML limpio. El resultado es más estable y más fácil de revisar en capturas.</p><h2>Aplicación en CoderUp</h2><p>Las tarjetas de cursos necesitan imagen, categoría, nivel, precio y llamada a la acción. Grid ayuda a mantener esa información alineada aunque cambie la longitud del texto o el número de resultados.</p><p>Además, una grilla bien definida mejora la accesibilidad visual: separa bloques, evita solapamientos y permite que cada sección tenga una jerarquía clara.</p><h2>Conclusión</h2><p>CSS Grid no sustituye a flexbox, pero es una herramienta clave para interfaces profesionales, responsive y fáciles de defender.</p>', 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?auto=format&fit=crop&w=1200&q=82', 4, 'CSS', JSON_ARRAY('css', 'grid', 'layout'), 9, TRUE, NOW()),
('API REST: respuestas claras para clientes', 'api-rest-mejores-practicas', 'Diseña endpoints previsibles, mensajes de error útiles y respuestas consistentes para que el frontend sea más fiable.', '<h2>Una API como contrato</h2><p>Una API REST no es solo una lista de archivos en backend. Es el contrato que permite que la interfaz muestre cursos, posts, instructores, cupones y pedidos sin adivinar cómo llegan los datos.</p><p>Cuando las respuestas mantienen una estructura consistente, el frontend puede enseñar mensajes claros: cursos cargados, cupón aplicado, pedido completado o error de validación. Esto mejora la experiencia del cliente porque cada acción tiene una respuesta comprensible.</p><h2>Seguridad y mantenimiento</h2><p>Las buenas prácticas incluyen validación de entrada, prepared statements, tokens de sesión y códigos HTTP correctos. Un error 400 comunica datos inválidos, un 401 falta de autenticación, un 404 recurso inexistente y un 500 un fallo inesperado.</p><p>También conviene paginar listados, documentar campos y evitar exponer detalles internos. Así la aplicación puede crecer sin romper las pantallas existentes.</p><h2>Conclusión</h2><p>Una API profesional falla bien, protege los datos y permite que la experiencia del cliente sea estable.</p>', 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=82', 2, 'Backend', JSON_ARRAY('api', 'rest', 'backend'), 10, TRUE, NOW()),
('Git Flow: organizar el trabajo en equipo', 'git-flow-workflow-equipos', 'Un flujo de ramas y revisiones ayuda a explicar cambios, evitar conflictos y mantener el proyecto listo para desplegar.', '<h2>Más que guardar versiones</h2><p>Git cuenta la historia técnica del proyecto. Un historial limpio permite ver qué se implementó, cuándo se corrigió un problema y cómo evolucionaron las decisiones principales.</p><p>Git Flow propone separar el trabajo en ramas de funcionalidad, corrección y publicación. En proyectos pequeños puede simplificarse, pero la idea central sigue siendo útil: aislar cambios, revisar antes de mezclar y mantener la rama principal estable.</p><h2>Aplicado a una plataforma real</h2><p>Antes de subir cambios conviene revisar el diff, ejecutar el build y comprobar que no se publican secretos. Este hábito evita errores visibles en producción y demuestra una forma profesional de trabajar.</p><p>Para un TFG, los commits también sirven como evidencia: muestran iteración, pruebas, mejoras visuales y correcciones sobre datos reales.</p><h2>Conclusión</h2><p>Un workflow claro reduce conflictos y convierte el repositorio en una parte defendible del producto.</p>', 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?auto=format&fit=crop&w=1200&q=82', 3, 'Git', JSON_ARRAY('git', 'workflow', 'devops'), 8, TRUE, NOW()),
('Docker para principiantes: del código al entorno', 'docker-para-principiantes', 'Entiende imágenes, contenedores, volúmenes y docker-compose con un enfoque práctico para despliegues reproducibles.', '<h2>El problema que resuelve Docker</h2><p>Docker reduce el clásico fallo de que una aplicación funciona en un equipo, pero no en otro. Una imagen define dependencias, versión del runtime y comando de arranque para que desarrollo y producción se parezcan más.</p><p>En una plataforma con frontend, backend y base de datos, docker-compose permite levantar varios servicios de forma coordinada. Esto facilita pruebas, despliegues y revisión técnica del proyecto.</p><h2>Buenas prácticas iniciales</h2><p>Un Dockerfile debe ser claro, pequeño y fácil de reconstruir. Conviene copiar dependencias antes que código cuando sea posible, definir variables de entorno y revisar logs para entender qué ocurre dentro del contenedor.</p><p>Docker no sustituye a las migraciones, la monitorización ni la seguridad, pero aporta una base muy sólida para trabajar con entornos repetibles.</p><h2>Conclusión</h2><p>Aprender Docker ayuda a pasar de una aplicación local a un producto desplegable con más confianza.</p>', 'https://images.unsplash.com/photo-1605745341112-85968b19335b?auto=format&fit=crop&w=1200&q=82', 3, 'DevOps', JSON_ARRAY('docker', 'containers', 'devops'), 8, TRUE, NOW()),
('Accesibilidad web práctica para plataformas de cursos', 'accesibilidad-web-practica', 'Mejora formularios, navegación, contraste, foco visible y mensajes de error para que más personas puedan usar la web.', '<h2>Accesibilidad como parte de la calidad</h2><p>Una web accesible no es una versión especial: es una web mejor construida. Etiquetas visibles, contraste suficiente, foco claro y mensajes de error comprensibles ayudan a todos los usuarios.</p><p>En CoderUp, los formularios de login, registro, checkout y recuperación de contraseña son momentos críticos. Si una persona no entiende qué campo falla o no puede navegar con teclado, el flujo de compra queda incompleto.</p><h2>Detalles que se notan</h2><p>Los botones deben comunicar estados de carga, los enlaces deben tener textos claros y las imágenes necesitan alternativas descriptivas cuando aportan información. También es importante mantener una jerarquía de encabezados lógica para lectores de pantalla.</p><p>La accesibilidad mejora las capturas porque la interfaz se ve ordenada, con separación clara entre acciones, contenido y mensajes del sistema.</p><h2>Conclusión</h2><p>Aplicar WCAG desde el diseño convierte la experiencia en algo más usable, profesional y respetuoso con los clientes.</p>', 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1200&q=82', 4, 'UX', JSON_ARRAY('accesibilidad', 'wcag', 'ux'), 7, TRUE, NOW()),
('MySQL para ecommerce educativo', 'mysql-ecommerce-educativo', 'Modela usuarios, cursos, pedidos, cupones e inscripciones con relaciones claras y datos preparados para auditoría.', '<h2>Datos que sostienen el producto</h2><p>Un ecommerce educativo necesita más que una tabla de cursos. Usuarios, pedidos, líneas de pedido, cupones e inscripciones forman un recorrido completo desde la visita hasta el acceso al contenido.</p><p>Cada compra debe conservar el precio pagado, el cupón aplicado y los cursos desbloqueados. Así el cliente puede consultar sus pedidos y el sistema mantiene información fiable aunque el precio de un curso cambie después.</p><h2>Relaciones y transacciones</h2><p>MySQL permite expresar estas conexiones con claves foráneas y tablas normalizadas. order_items separa los cursos comprados de la orden, enrollments registra el acceso posterior y coupons permite reglas comerciales sin tocar la interfaz.</p><p>Las transacciones son esenciales: crear orden, items e inscripciones debe ocurrir como una sola operación. Si algo falla, se revierte para no dejar datos a medias.</p><h2>Conclusión</h2><p>Un modelo relacional claro convierte el checkout en una funcionalidad defendible, segura y fácil de explicar.</p>', 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=1200&q=82', 2, 'Bases de Datos', JSON_ARRAY('mysql', 'sql', 'ecommerce'), 8, TRUE, NOW()),
('IA generativa en plataformas educativas', 'ia-generativa-plataformas-educativas', 'Cómo usar asistentes, recomendaciones y automatización sin perder claridad, privacidad ni control del contenido.', '<h2>IA con propósito</h2><p>La inteligencia artificial aporta valor cuando resuelve una necesidad concreta: resumir lecciones, sugerir rutas de aprendizaje, responder dudas frecuentes o ayudar al equipo a clasificar contenidos.</p><p>En una plataforma educativa no basta con conectar un modelo. Hay que decidir qué datos puede leer, qué límites tendrá y cómo se comprobará que sus respuestas son útiles para el cliente.</p><h2>Diseño responsable</h2><p>Los prompts deben ser claros, los resultados deben revisarse y la interfaz debe explicar cuándo una respuesta ha sido generada automáticamente. También es importante evitar enviar datos personales innecesarios a servicios externos.</p><p>Medir calidad ayuda a mejorar: tiempo ahorrado, satisfacción del usuario, precisión de respuestas y reducción de dudas repetidas.</p><h2>Conclusión</h2><p>La IA bien integrada no sustituye el contenido del curso; lo hace más accesible, guiado y práctico.</p>', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=82', 2, 'IA', JSON_ARRAY('ia', 'educacion', 'automatizacion'), 9, TRUE, NOW()),
('Checklist de ciberseguridad antes de publicar', 'checklist-ciberseguridad-publicar', 'Una lista práctica para revisar autenticación, formularios, permisos, cabeceras, logs y variables antes del despliegue.', '<h2>Seguridad antes del deploy</h2><p>Publicar una aplicación implica revisar más que el diseño. Formularios, sesiones, roles, permisos, cupones y endpoints deben resistir entradas inválidas y accesos no autorizados.</p><p>Un checklist sencillo evita errores frecuentes: validar datos en backend, usar consultas preparadas, proteger tokens, configurar variables de entorno y no mostrar mensajes internos al usuario.</p><h2>Lo que debe comprobarse</h2><p>Las cabeceras de seguridad, el control de CORS, el manejo de errores y los logs son parte de la experiencia profesional. Si algo falla, el sistema debe informar sin exponer detalles sensibles.</p><p>También conviene revisar cuentas demo, contraseñas, rutas de administración y permisos por rol antes de hacer capturas o defensa.</p><h2>Conclusión</h2><p>Una revisión de seguridad convierte el proyecto en un producto más serio y defendible.</p>', 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=82', 3, 'Ciberseguridad', JSON_ARRAY('seguridad', 'owasp', 'deploy'), 8, TRUE, NOW()),
('Cómo preparar datos para machine learning', 'preparar-datos-machine-learning', 'Antes de entrenar un modelo, los datos deben limpiarse, entenderse y validarse con criterios claros.', '<h2>El modelo empieza en los datos</h2><p>Machine learning no consiste solo en ejecutar una librería. La calidad del resultado depende de cómo se preparan los datos, qué columnas se seleccionan y qué errores se detectan antes de entrenar.</p><p>Valores vacíos, duplicados, escalas distintas y categorías mal codificadas pueden cambiar por completo la predicción. Por eso la exploración inicial es una fase esencial.</p><h2>Proceso recomendado</h2><p>Primero se entiende el objetivo del modelo. Después se limpian datos, se separa entrenamiento y validación, se eligen métricas y se comparan resultados con una línea base simple.</p><p>Documentar ese proceso permite explicar por qué se eligió un modelo y qué limitaciones tiene.</p><h2>Conclusión</h2><p>Preparar bien los datos ahorra tiempo, mejora resultados y hace que un proyecto de IA sea más transparente.</p>', 'https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=1200&q=82', 2, 'IA', JSON_ARRAY('machine-learning', 'python', 'datos'), 9, TRUE, NOW()),
('Testing que sí aporta valor al frontend', 'testing-aporta-valor-frontend', 'Pruebas enfocadas en flujos reales: filtros, formularios, carrito, accesibilidad y estados de error.', '<h2>Probar comportamiento, no implementación</h2><p>Un buen test frontend se parece a lo que haría una persona usuaria: buscar un curso, aplicar un filtro, añadir al carrito o leer un mensaje de error. Eso aporta más valor que comprobar detalles internos frágiles.</p><p>Las pruebas deben cubrir estados críticos: carga, vacío, error, éxito y permisos. Así el equipo detecta fallos antes de que aparezcan en producción.</p><h2>Accesibilidad y confianza</h2><p>React Testing Library anima a buscar elementos por rol, etiqueta o texto visible. Esto favorece componentes más accesibles y más cercanos a la experiencia real.</p><p>Combinado con CI, el testing permite desplegar cambios con menos miedo y explicar mejor la calidad del proyecto.</p><h2>Conclusión</h2><p>Los tests útiles no ralentizan el desarrollo: protegen los flujos que más importan al cliente.</p>', 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=82', 1, 'Testing', JSON_ARRAY('testing', 'frontend', 'calidad'), 7, TRUE, NOW()),
('Laravel para APIs mantenibles', 'laravel-apis-mantenibles', 'Estructura rutas, controladores, validaciones, recursos y autenticación para crear backends ordenados.', '<h2>Orden en el backend</h2><p>Laravel ayuda a construir APIs con una estructura clara. Rutas, controladores, modelos y migraciones tienen un lugar definido, lo que facilita entender el proyecto incluso cuando crece.</p><p>Para una plataforma de cursos, esa organización permite separar usuarios, cursos, pedidos, cupones e inscripciones sin mezclar responsabilidades.</p><h2>Buenas prácticas</h2><p>Las validaciones deben vivir en backend, las respuestas JSON deben ser consistentes y los recursos ayudan a decidir qué campos se exponen al frontend. La autenticación y los permisos protegen zonas privadas como el panel de administración.</p><p>Además, las migraciones documentan cómo evoluciona la base de datos.</p><h2>Conclusión</h2><p>Laravel es una buena opción cuando se busca productividad sin renunciar a una arquitectura fácil de mantener.</p>', 'https://images.unsplash.com/photo-1599507593499-a3f7d7d97667?auto=format&fit=crop&w=1200&q=82', 2, 'Backend', JSON_ARRAY('laravel', 'php', 'api'), 8, TRUE, NOW()),
('Automatizar builds con GitHub Actions', 'automatizar-builds-github-actions', 'Configura workflows para ejecutar build, tests y despliegues con cada cambio importante del repositorio.', '<h2>Automatización visible</h2><p>GitHub Actions permite convertir tareas repetitivas en workflows. Cada push puede ejecutar instalación de dependencias, build, tests y comprobaciones básicas de calidad.</p><p>Esto aporta confianza al equipo y también mejora la defensa del proyecto: se ve que el repositorio no solo contiene código, sino un proceso de entrega.</p><h2>Qué automatizar primero</h2><p>Lo más útil suele ser empezar por build y tests. Después se pueden añadir lint, auditoría de dependencias, generación de artefactos y despliegue controlado con secrets.</p><p>Un workflow claro debe tener nombres descriptivos, jobs separados y logs fáciles de interpretar.</p><h2>Conclusión</h2><p>Automatizar el pipeline reduce errores manuales y hace que el proyecto parezca más profesional desde la primera captura.</p>', 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?auto=format&fit=crop&w=1200&q=82', 3, 'Automatización', JSON_ARRAY('github-actions', 'ci-cd', 'devops'), 7, TRUE, NOW());

-- Cupones
INSERT INTO coupons (code, description, discount_type, discount_value, min_items, max_items, max_uses, uses, only_new_users, active, expires_at) VALUES
('WELCOME20', 'Descuento 20% primera compra', 'percentage', 20.00, 1, NULL, -1, 0, TRUE, TRUE, NULL),
('SUMMER10', 'Descuento verano 10%', 'percentage', 10.00, 1, NULL, -1, 0, FALSE, TRUE, DATE_ADD(NOW(), INTERVAL 6 MONTH)),
('BUY3', 'Compra 3 o más cursos y recibe 15% descuento', 'buy_x_get_discount', 15.00, 3, NULL, -1, 0, FALSE, TRUE, NULL),
('BUY5', 'Compra 5 o más cursos y recibe 25% descuento', 'buy_x_get_discount', 25.00, 5, NULL, -1, 0, FALSE, TRUE, NULL),
('BUNDLE30', 'Bundle especial con 30 euros de descuento', 'fixed', 30.00, 2, NULL, -1, 0, FALSE, TRUE, NULL);

-- Pedido e inscripciones demo
INSERT INTO orders (id, user_id, order_number, subtotal, discount_amount, discount_percent, coupon_code, total, status) VALUES
(1, 3, 'ORD-20260514-1001', 89.98, 17.99, 20.00, 'WELCOME20', 71.99, 'completed');

INSERT INTO order_items (order_id, course_id, price_at_purchase) VALUES
(1, 1, 49.99),
(1, 2, 39.99);

INSERT INTO enrollments (user_id, course_id, progress, status) VALUES
(3, 1, 45, 'enrolled'),
(3, 2, 100, 'completed');
