INSERT INTO categories (id, name, slug, description, icon) VALUES
(6, 'IA', 'ia', 'Inteligencia artificial aplicada, automatización y machine learning', 'brain-circuit'),
(7, 'Ciberseguridad', 'ciberseguridad', 'Seguridad web, auditoría, protección de datos y hardening', 'shield-check')
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  description = VALUES(description),
  icon = VALUES(icon);

INSERT INTO courses (id, title, slug, description, thumbnail_url, price, level, category_id, instructor_id, duration_hours, total_lessons, total_students, rating, `requires`, what_you_learn, curriculum, is_published) VALUES
(13, 'Inteligencia Artificial para Developers', 'inteligencia-artificial-developers', 'Aprende a integrar IA generativa en aplicaciones reales: prompts, embeddings, asistentes, automatización y evaluación de respuestas. Un curso práctico para crear funciones útiles, medibles y seguras.', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=82', 64.99, 'Intermedio', 6, 2, 30, 44, 1450, 4.80, JSON_ARRAY('JavaScript o Python básico', 'HTTP y APIs'), JSON_ARRAY('Prompts robustos', 'Embeddings', 'Asistentes con contexto', 'Automatización', 'Evaluación de respuestas', 'Costes y límites', 'Privacidad', 'Deploy'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Fundamentos de IA aplicada', 'lecciones', JSON_ARRAY('Modelos', 'Prompts', 'Tokens')), JSON_OBJECT('nombre', 'Integración en producto', 'lecciones', JSON_ARRAY('APIs', 'Embeddings', 'RAG básico')), JSON_OBJECT('nombre', 'Proyecto final', 'lecciones', JSON_ARRAY('Asistente de estudio', 'Evaluación', 'Deploy')))), TRUE),
(14, 'Ciberseguridad Web Esencial', 'ciberseguridad-web-esencial', 'Protege aplicaciones web con fundamentos de seguridad, OWASP Top 10, validación, autenticación, control de sesiones y buenas prácticas para despliegues más seguros.', 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=82', 54.99, 'Intermedio', 7, 3, 28, 40, 980, 4.70, JSON_ARRAY('HTML y JavaScript básico', 'Conceptos de backend'), JSON_ARRAY('OWASP Top 10', 'Validación segura', 'Autenticación', 'Control de sesiones', 'Protección de APIs', 'Headers de seguridad', 'Logs', 'Checklist de despliegue'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Amenazas comunes', 'lecciones', JSON_ARRAY('XSS', 'SQL Injection', 'CSRF')), JSON_OBJECT('nombre', 'Defensa en backend', 'lecciones', JSON_ARRAY('Validación', 'Tokens', 'Permisos')), JSON_OBJECT('nombre', 'Auditoría básica', 'lecciones', JSON_ARRAY('Headers', 'Logs', 'Checklist')))), TRUE),
(15, 'Machine Learning con Python', 'machine-learning-python', 'Construye modelos de machine learning desde cero con Python, pandas, scikit-learn y métricas de evaluación. Ideal para entender datos antes de llevar IA a producción.', 'https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=1200&q=82', 59.99, 'Intermedio', 6, 2, 34, 46, 1320, 4.80, JSON_ARRAY('Python básico', 'Álgebra básica'), JSON_ARRAY('Limpieza de datos', 'Pandas', 'Modelos supervisados', 'Validación', 'Métricas', 'Pipelines', 'Visualización', 'Proyecto predictivo'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Datos', 'lecciones', JSON_ARRAY('CSV', 'Pandas', 'Limpieza')), JSON_OBJECT('nombre', 'Modelos', 'lecciones', JSON_ARRAY('Regresión', 'Clasificación', 'Métricas')), JSON_OBJECT('nombre', 'Proyecto', 'lecciones', JSON_ARRAY('Dataset real', 'Entrenamiento', 'Informe')))), TRUE),
(16, 'Testing Frontend Profesional', 'testing-frontend-profesional', 'Asegura interfaces con Vitest, React Testing Library, mocks, pruebas de accesibilidad y criterios de calidad antes del despliegue.', 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=82', 44.99, 'Intermedio', 1, 1, 22, 34, 870, 4.70, JSON_ARRAY('JavaScript', 'React básico'), JSON_ARRAY('Tests unitarios', 'Testing Library', 'Mocks', 'Accesibilidad', 'Cobertura útil', 'CI', 'Refactor seguro', 'Debug de fallos'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Fundamentos', 'lecciones', JSON_ARRAY('Arrange Act Assert', 'Vitest', 'Matchers')), JSON_OBJECT('nombre', 'Componentes', 'lecciones', JSON_ARRAY('Queries', 'Eventos', 'Mocks')), JSON_OBJECT('nombre', 'Calidad continua', 'lecciones', JSON_ARRAY('Coverage', 'CI', 'A11y')))), TRUE),
(17, 'Laravel y PHP Moderno', 'laravel-php-moderno', 'Desarrolla aplicaciones backend con Laravel, Eloquent, migraciones, validación, autenticación y APIs listas para conectar con frontends modernos.', 'https://images.unsplash.com/photo-1599507593499-a3f7d7d97667?auto=format&fit=crop&w=1200&q=82', 49.99, 'Intermedio', 2, 2, 32, 42, 1180, 4.70, JSON_ARRAY('PHP básico', 'SQL básico'), JSON_ARRAY('Rutas y controladores', 'Eloquent ORM', 'Migraciones', 'Validación', 'Autenticación', 'APIs JSON', 'Testing', 'Deploy'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Laravel base', 'lecciones', JSON_ARRAY('Instalación', 'Rutas', 'Controladores')), JSON_OBJECT('nombre', 'Datos', 'lecciones', JSON_ARRAY('Migraciones', 'Modelos', 'Relaciones')), JSON_OBJECT('nombre', 'API', 'lecciones', JSON_ARRAY('Resources', 'Auth', 'Deploy')))), TRUE),
(18, 'Automatización con GitHub Actions', 'automatizacion-github-actions', 'Crea pipelines de CI/CD para builds, tests, análisis de calidad y despliegues automáticos con workflows claros y mantenibles.', 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?auto=format&fit=crop&w=1200&q=82', 34.99, 'Intermedio', 3, 3, 18, 30, 760, 4.60, JSON_ARRAY('Git básico', 'npm o Composer'), JSON_ARRAY('Workflows YAML', 'Jobs y steps', 'Secrets', 'Build automático', 'Tests en CI', 'Deploy', 'Badges', 'Buenas prácticas'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'CI base', 'lecciones', JSON_ARRAY('Workflow', 'Jobs', 'Cache')), JSON_OBJECT('nombre', 'Calidad', 'lecciones', JSON_ARRAY('Tests', 'Lint', 'Artifacts')), JSON_OBJECT('nombre', 'Deploy', 'lecciones', JSON_ARRAY('Secrets', 'Environments', 'Rollback')))), TRUE)
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  description = VALUES(description),
  thumbnail_url = VALUES(thumbnail_url),
  price = VALUES(price),
  level = VALUES(level),
  category_id = VALUES(category_id),
  instructor_id = VALUES(instructor_id),
  duration_hours = VALUES(duration_hours),
  total_lessons = VALUES(total_lessons),
  total_students = VALUES(total_students),
  rating = VALUES(rating),
  `requires` = VALUES(`requires`),
  what_you_learn = VALUES(what_you_learn),
  curriculum = VALUES(curriculum),
  is_published = VALUES(is_published);

INSERT INTO posts (title, slug, excerpt, content, cover_image_url, author_id, category, tags, read_time_minutes, is_published, published_at) VALUES
('IA generativa en plataformas educativas', 'ia-generativa-plataformas-educativas', 'Cómo usar asistentes, recomendaciones y automatización sin perder claridad, privacidad ni control del contenido.', '<h2>IA con propósito</h2><p>La inteligencia artificial aporta valor cuando resuelve una necesidad concreta: resumir lecciones, sugerir rutas de aprendizaje, responder dudas frecuentes o ayudar al equipo a clasificar contenidos.</p><p>En una plataforma educativa no basta con conectar un modelo. Hay que decidir qué datos puede leer, qué límites tendrá y cómo se comprobará que sus respuestas son útiles para el cliente.</p><h2>Diseño responsable</h2><p>Los prompts deben ser claros, los resultados deben revisarse y la interfaz debe explicar cuándo una respuesta ha sido generada automáticamente. También es importante evitar enviar datos personales innecesarios a servicios externos.</p><p>Medir calidad ayuda a mejorar: tiempo ahorrado, satisfacción del usuario, precisión de respuestas y reducción de dudas repetidas.</p><h2>Conclusión</h2><p>La IA bien integrada no sustituye el contenido del curso; lo hace más accesible, guiado y práctico.</p>', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=82', 2, 'IA', JSON_ARRAY('ia', 'educacion', 'automatizacion'), 9, TRUE, NOW()),
('Checklist de ciberseguridad antes de publicar', 'checklist-ciberseguridad-publicar', 'Una lista práctica para revisar autenticación, formularios, permisos, cabeceras, logs y variables antes del despliegue.', '<h2>Seguridad antes del deploy</h2><p>Publicar una aplicación implica revisar más que el diseño. Formularios, sesiones, roles, permisos, cupones y endpoints deben resistir entradas inválidas y accesos no autorizados.</p><p>Un checklist sencillo evita errores frecuentes: validar datos en backend, usar consultas preparadas, proteger tokens, configurar variables de entorno y no mostrar mensajes internos al usuario.</p><h2>Lo que debe comprobarse</h2><p>Las cabeceras de seguridad, el control de CORS, el manejo de errores y los logs son parte de la experiencia profesional. Si algo falla, el sistema debe informar sin exponer detalles sensibles.</p><p>También conviene revisar cuentas demo, contraseñas, rutas de administración y permisos por rol antes de hacer capturas o defensa.</p><h2>Conclusión</h2><p>Una revisión de seguridad convierte el proyecto en un producto más serio y defendible.</p>', 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=82', 3, 'Ciberseguridad', JSON_ARRAY('seguridad', 'owasp', 'deploy'), 8, TRUE, NOW()),
('Cómo preparar datos para machine learning', 'preparar-datos-machine-learning', 'Antes de entrenar un modelo, los datos deben limpiarse, entenderse y validarse con criterios claros.', '<h2>El modelo empieza en los datos</h2><p>Machine learning no consiste solo en ejecutar una librería. La calidad del resultado depende de cómo se preparan los datos, qué columnas se seleccionan y qué errores se detectan antes de entrenar.</p><p>Valores vacíos, duplicados, escalas distintas y categorías mal codificadas pueden cambiar por completo la predicción. Por eso la exploración inicial es una fase esencial.</p><h2>Proceso recomendado</h2><p>Primero se entiende el objetivo del modelo. Después se limpian datos, se separa entrenamiento y validación, se eligen métricas y se comparan resultados con una línea base simple.</p><p>Documentar ese proceso permite explicar por qué se eligió un modelo y qué limitaciones tiene.</p><h2>Conclusión</h2><p>Preparar bien los datos ahorra tiempo, mejora resultados y hace que un proyecto de IA sea más transparente.</p>', 'https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=1200&q=82', 2, 'IA', JSON_ARRAY('machine-learning', 'python', 'datos'), 9, TRUE, NOW()),
('Testing que sí aporta valor al frontend', 'testing-aporta-valor-frontend', 'Pruebas enfocadas en flujos reales: filtros, formularios, carrito, accesibilidad y estados de error.', '<h2>Probar comportamiento, no implementación</h2><p>Un buen test frontend se parece a lo que haría una persona usuaria: buscar un curso, aplicar un filtro, añadir al carrito o leer un mensaje de error. Eso aporta más valor que comprobar detalles internos frágiles.</p><p>Las pruebas deben cubrir estados críticos: carga, vacío, error, éxito y permisos. Así el equipo detecta fallos antes de que aparezcan en producción.</p><h2>Accesibilidad y confianza</h2><p>React Testing Library anima a buscar elementos por rol, etiqueta o texto visible. Esto favorece componentes más accesibles y más cercanos a la experiencia real.</p><p>Combinado con CI, el testing permite desplegar cambios con menos miedo y explicar mejor la calidad del proyecto.</p><h2>Conclusión</h2><p>Los tests útiles no ralentizan el desarrollo: protegen los flujos que más importan al cliente.</p>', 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=82', 1, 'Testing', JSON_ARRAY('testing', 'frontend', 'calidad'), 7, TRUE, NOW()),
('Laravel para APIs mantenibles', 'laravel-apis-mantenibles', 'Estructura rutas, controladores, validaciones, recursos y autenticación para crear backends ordenados.', '<h2>Orden en el backend</h2><p>Laravel ayuda a construir APIs con una estructura clara. Rutas, controladores, modelos y migraciones tienen un lugar definido, lo que facilita entender el proyecto incluso cuando crece.</p><p>Para una plataforma de cursos, esa organización permite separar usuarios, cursos, pedidos, cupones e inscripciones sin mezclar responsabilidades.</p><h2>Buenas prácticas</h2><p>Las validaciones deben vivir en backend, las respuestas JSON deben ser consistentes y los recursos ayudan a decidir qué campos se exponen al frontend. La autenticación y los permisos protegen zonas privadas como el panel de administración.</p><p>Además, las migraciones documentan cómo evoluciona la base de datos.</p><h2>Conclusión</h2><p>Laravel es una buena opción cuando se busca productividad sin renunciar a una arquitectura fácil de mantener.</p>', 'https://images.unsplash.com/photo-1599507593499-a3f7d7d97667?auto=format&fit=crop&w=1200&q=82', 2, 'Backend', JSON_ARRAY('laravel', 'php', 'api'), 8, TRUE, NOW()),
('Automatizar builds con GitHub Actions', 'automatizar-builds-github-actions', 'Configura workflows para ejecutar build, tests y despliegues con cada cambio importante del repositorio.', '<h2>Automatización visible</h2><p>GitHub Actions permite convertir tareas repetitivas en workflows. Cada push puede ejecutar instalación de dependencias, build, tests y comprobaciones básicas de calidad.</p><p>Esto aporta confianza al equipo y también mejora la defensa del proyecto: se ve que el repositorio no solo contiene código, sino un proceso de entrega.</p><h2>Qué automatizar primero</h2><p>Lo más útil suele ser empezar por build y tests. Después se pueden añadir lint, auditoría de dependencias, generación de artefactos y despliegue controlado con secrets.</p><p>Un workflow claro debe tener nombres descriptivos, jobs separados y logs fáciles de interpretar.</p><h2>Conclusión</h2><p>Automatizar el pipeline reduce errores manuales y hace que el proyecto parezca más profesional desde la primera captura.</p>', 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?auto=format&fit=crop&w=1200&q=82', 3, 'Automatización', JSON_ARRAY('github-actions', 'ci-cd', 'devops'), 7, TRUE, NOW())
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  excerpt = VALUES(excerpt),
  content = VALUES(content),
  cover_image_url = VALUES(cover_image_url),
  author_id = VALUES(author_id),
  category = VALUES(category),
  tags = VALUES(tags),
  read_time_minutes = VALUES(read_time_minutes),
  is_published = VALUES(is_published);
