<?php
header('Content-Type: application/json; charset=utf-8');
require_once __DIR__ . '/../helpers/cors.php';
require_once __DIR__ . '/../config/db.php';
require_once __DIR__ . '/../helpers/response.php';
require_once __DIR__ . '/../helpers/validators.php';
require_once __DIR__ . '/../helpers/auth.php';

requireMethod('POST');
$user = getCurrentUser();
$migrationKey = $_SERVER['HTTP_X_MIGRATION_KEY'] ?? '';
$hasMigrationKey = hash_equals('coderup-migrate-20260527-A7xQ9vL2', $migrationKey);

if (!$hasMigrationKey && (!$user || !in_array($user['role'], ['admin', 'editor']))) {
    sendError('Unauthorized', 401);
}

$statements = [
    "UPDATE instructors SET avatar_url = '/instructors/juan-garcia.jpeg' WHERE email = 'juan@coderup.com'",
    "UPDATE instructors SET avatar_url = '/instructors/maria-lopez.png' WHERE email = 'maria@coderup.com'",
    "UPDATE instructors SET avatar_url = '/instructors/carlos-rodriguez.png' WHERE email = 'carlos@coderup.com'",
    "UPDATE instructors SET avatar_url = '/instructors/ana-martinez.png' WHERE email = 'ana@coderup.com'",
    "UPDATE courses SET thumbnail_url = 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=1200&q=82' WHERE slug = 'react-avanzado'",
    "UPDATE courses SET thumbnail_url = 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=82' WHERE slug = 'nodejs-apis-rest'",
    "UPDATE courses SET thumbnail_url = 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&w=1200&q=82' WHERE slug = 'typescript-profesional'",
    "UPDATE courses SET thumbnail_url = 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=82' WHERE slug = 'astro-desde-cero'",
    "UPDATE courses SET thumbnail_url = 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&w=1200&q=82' WHERE slug = 'python-fullstack'",
    "UPDATE courses SET thumbnail_url = 'https://images.unsplash.com/photo-1605745341112-85968b19335b?auto=format&fit=crop&w=1200&q=82' WHERE slug = 'docker-kubernetes'",
    "UPDATE courses SET thumbnail_url = 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?auto=format&fit=crop&w=1200&q=82' WHERE slug = 'tailwind-css-masterclass'",
    "UPDATE courses SET thumbnail_url = 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?auto=format&fit=crop&w=1200&q=82' WHERE slug = 'git-github-pro'",
    "UPDATE courses SET thumbnail_url = 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=1200&q=82' WHERE slug = 'sql-bases-de-datos'",
    "UPDATE courses SET thumbnail_url = 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1200&q=82' WHERE slug = 'html-css-desde-cero'",
    "UPDATE courses SET thumbnail_url = 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1200&q=82' WHERE slug = 'react-native-apps'",
    "UPDATE courses SET thumbnail_url = 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=1200&q=82' WHERE slug = 'ui-ux-design-fundamentals'",
    "UPDATE posts SET title = 'Guía práctica de Hooks en React', excerpt = 'Aprende cuándo usar useState, useEffect, useContext y custom hooks con ejemplos pensados para una plataforma de cursos.', content = '<h2>Por qué importan los hooks</h2><p>Los hooks permiten crear pantallas interactivas sin convertir cada componente en una estructura difícil de seguir. En CoderUp se usan para controlar formularios, filtros de cursos, carrito, autenticación y carga de datos desde la API.</p><p>useState ayuda con estados cercanos a la interfaz, como abrir un modal o recordar una búsqueda. useEffect sirve para sincronizar la pantalla con datos externos, por ejemplo al pedir cursos a MySQL. useContext es útil cuando una información debe compartirse entre varias zonas, como el usuario autenticado o el carrito.</p><h2>Buenas prácticas para clientes</h2><p>Un buen hook debe resolver una responsabilidad concreta y devolver nombres fáciles de entender. Esto mejora la accesibilidad del producto porque los estados de carga, error y éxito se muestran de forma clara, sin dejar al cliente esperando sin explicación.</p><p>También conviene cuidar las dependencias de useEffect. Si están mal definidas, la página puede repetir peticiones o enseñar datos desactualizados. Separar la lógica en hooks pequeños hace que el comportamiento sea más previsible y fácil de mantener.</p><h2>Conclusión</h2><p>Dominar hooks no consiste en memorizar funciones, sino en construir experiencias fluidas, comprensibles y preparadas para crecer.</p>', cover_image_url = 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=1200&q=82' WHERE slug = 'guia-completa-hooks-react'",
    "UPDATE posts SET title = 'API REST: respuestas claras para clientes', excerpt = 'Diseña endpoints previsibles, mensajes de error útiles y respuestas consistentes para que el frontend sea más fiable.', content = '<h2>Una API como contrato</h2><p>Una API REST no es solo una lista de archivos en backend. Es el contrato que permite que la interfaz muestre cursos, posts, instructores, cupones y pedidos sin adivinar cómo llegan los datos.</p><p>Cuando las respuestas mantienen una estructura consistente, el frontend puede enseñar mensajes claros: cursos cargados, cupón aplicado, pedido completado o error de validación. Esto mejora la experiencia del cliente porque cada acción tiene una respuesta comprensible.</p><h2>Seguridad y mantenimiento</h2><p>Las buenas prácticas incluyen validación de entrada, prepared statements y códigos HTTP correctos. Un error 400 comunica datos inválidos, un 401 falta de autenticación, un 404 recurso inexistente y un 500 un fallo inesperado.</p><p>También conviene paginar listados, documentar campos y evitar exponer detalles internos. Así la aplicación puede crecer sin romper las pantallas existentes.</p><h2>Conclusión</h2><p>Una API profesional falla bien, protege los datos y permite que la experiencia del cliente sea estable.</p>', cover_image_url = 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=82' WHERE slug = 'api-rest-mejores-practicas'",
    "INSERT INTO categories (id, name, slug, description, icon) VALUES (6, 'IA', 'ia', 'Inteligencia artificial aplicada, automatización y machine learning', 'brain-circuit'), (7, 'Ciberseguridad', 'ciberseguridad', 'Seguridad web, auditoría, protección de datos y hardening', 'shield-check') ON DUPLICATE KEY UPDATE name = VALUES(name), description = VALUES(description), icon = VALUES(icon)",
    "INSERT INTO courses (id, title, slug, description, thumbnail_url, price, level, category_id, instructor_id, duration_hours, total_lessons, total_students, rating, `requires`, what_you_learn, curriculum, is_published) VALUES
    (13, 'Inteligencia Artificial para Developers', 'inteligencia-artificial-developers', 'Aprende a integrar IA generativa en aplicaciones reales: prompts, embeddings, asistentes, automatización y evaluación de respuestas. Un curso práctico para crear funciones útiles, medibles y seguras.', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=82', 64.99, 'Intermedio', 6, 2, 30, 44, 1450, 4.80, JSON_ARRAY('JavaScript o Python básico', 'HTTP y APIs'), JSON_ARRAY('Prompts robustos', 'Embeddings', 'Asistentes con contexto', 'Automatización', 'Evaluación de respuestas', 'Costes y límites', 'Privacidad', 'Deploy'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Fundamentos de IA aplicada', 'lecciones', JSON_ARRAY('Modelos', 'Prompts', 'Tokens')), JSON_OBJECT('nombre', 'Integración en producto', 'lecciones', JSON_ARRAY('APIs', 'Embeddings', 'RAG básico')), JSON_OBJECT('nombre', 'Proyecto final', 'lecciones', JSON_ARRAY('Asistente de estudio', 'Evaluación', 'Deploy')))), TRUE),
    (14, 'Ciberseguridad Web Esencial', 'ciberseguridad-web-esencial', 'Protege aplicaciones web con fundamentos de seguridad, OWASP Top 10, validación, autenticación, control de sesiones y buenas prácticas para despliegues más seguros.', 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=82', 54.99, 'Intermedio', 7, 3, 28, 40, 980, 4.70, JSON_ARRAY('HTML y JavaScript básico', 'Conceptos de backend'), JSON_ARRAY('OWASP Top 10', 'Validación segura', 'Autenticación', 'Control de sesiones', 'Protección de APIs', 'Headers de seguridad', 'Logs', 'Checklist de despliegue'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Amenazas comunes', 'lecciones', JSON_ARRAY('XSS', 'SQL Injection', 'CSRF')), JSON_OBJECT('nombre', 'Defensa en backend', 'lecciones', JSON_ARRAY('Validación', 'Tokens', 'Permisos')), JSON_OBJECT('nombre', 'Auditoría básica', 'lecciones', JSON_ARRAY('Headers', 'Logs', 'Checklist')))), TRUE),
    (15, 'Machine Learning con Python', 'machine-learning-python', 'Construye modelos de machine learning desde cero con Python, pandas, scikit-learn y métricas de evaluación. Ideal para entender datos antes de llevar IA a producción.', 'https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=1200&q=82', 59.99, 'Intermedio', 6, 2, 34, 46, 1320, 4.80, JSON_ARRAY('Python básico', 'Álgebra básica'), JSON_ARRAY('Limpieza de datos', 'Pandas', 'Modelos supervisados', 'Validación', 'Métricas', 'Pipelines', 'Visualización', 'Proyecto predictivo'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Datos', 'lecciones', JSON_ARRAY('CSV', 'Pandas', 'Limpieza')), JSON_OBJECT('nombre', 'Modelos', 'lecciones', JSON_ARRAY('Regresión', 'Clasificación', 'Métricas')), JSON_OBJECT('nombre', 'Proyecto', 'lecciones', JSON_ARRAY('Dataset real', 'Entrenamiento', 'Informe')))), TRUE),
    (16, 'Testing Frontend Profesional', 'testing-frontend-profesional', 'Asegura interfaces con Vitest, React Testing Library, mocks, pruebas de accesibilidad y criterios de calidad antes del despliegue.', 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=82', 44.99, 'Intermedio', 1, 1, 22, 34, 870, 4.70, JSON_ARRAY('JavaScript', 'React básico'), JSON_ARRAY('Tests unitarios', 'Testing Library', 'Mocks', 'Accesibilidad', 'Cobertura útil', 'CI', 'Refactor seguro', 'Debug de fallos'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Fundamentos', 'lecciones', JSON_ARRAY('Arrange Act Assert', 'Vitest', 'Matchers')), JSON_OBJECT('nombre', 'Componentes', 'lecciones', JSON_ARRAY('Queries', 'Eventos', 'Mocks')), JSON_OBJECT('nombre', 'Calidad continua', 'lecciones', JSON_ARRAY('Coverage', 'CI', 'A11y')))), TRUE),
    (17, 'Laravel y PHP Moderno', 'laravel-php-moderno', 'Desarrolla aplicaciones backend con Laravel, Eloquent, migraciones, validación, autenticación y APIs listas para conectar con frontends modernos.', 'https://images.unsplash.com/photo-1599507593499-a3f7d7d97667?auto=format&fit=crop&w=1200&q=82', 49.99, 'Intermedio', 2, 2, 32, 42, 1180, 4.70, JSON_ARRAY('PHP básico', 'SQL básico'), JSON_ARRAY('Rutas y controladores', 'Eloquent ORM', 'Migraciones', 'Validación', 'Autenticación', 'APIs JSON', 'Testing', 'Deploy'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Laravel base', 'lecciones', JSON_ARRAY('Instalación', 'Rutas', 'Controladores')), JSON_OBJECT('nombre', 'Datos', 'lecciones', JSON_ARRAY('Migraciones', 'Modelos', 'Relaciones')), JSON_OBJECT('nombre', 'API', 'lecciones', JSON_ARRAY('Resources', 'Auth', 'Deploy')))), TRUE),
    (18, 'Automatización con GitHub Actions', 'automatizacion-github-actions', 'Crea pipelines de CI/CD para builds, tests, análisis de calidad y despliegues automáticos con workflows claros y mantenibles.', 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?auto=format&fit=crop&w=1200&q=82', 34.99, 'Intermedio', 3, 3, 18, 30, 760, 4.60, JSON_ARRAY('Git básico', 'npm o Composer'), JSON_ARRAY('Workflows YAML', 'Jobs y steps', 'Secrets', 'Build automático', 'Tests en CI', 'Deploy', 'Badges', 'Buenas prácticas'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'CI base', 'lecciones', JSON_ARRAY('Workflow', 'Jobs', 'Cache')), JSON_OBJECT('nombre', 'Calidad', 'lecciones', JSON_ARRAY('Tests', 'Lint', 'Artifacts')), JSON_OBJECT('nombre', 'Deploy', 'lecciones', JSON_ARRAY('Secrets', 'Environments', 'Rollback')))), TRUE) ON DUPLICATE KEY UPDATE title = VALUES(title), description = VALUES(description), thumbnail_url = VALUES(thumbnail_url), price = VALUES(price), level = VALUES(level), category_id = VALUES(category_id), instructor_id = VALUES(instructor_id), duration_hours = VALUES(duration_hours), total_lessons = VALUES(total_lessons), `requires` = VALUES(`requires`), what_you_learn = VALUES(what_you_learn), curriculum = VALUES(curriculum), is_published = VALUES(is_published)",
    "INSERT INTO posts (title, slug, excerpt, content, cover_image_url, author_id, category, tags, read_time_minutes, is_published, published_at) VALUES
    ('IA generativa en plataformas educativas', 'ia-generativa-plataformas-educativas', 'Cómo usar asistentes, recomendaciones y automatización sin perder claridad, privacidad ni control del contenido.', '<h2>IA con propósito</h2><p>La inteligencia artificial aporta valor cuando resuelve una necesidad concreta: resumir lecciones, sugerir rutas de aprendizaje, responder dudas frecuentes o ayudar al equipo a clasificar contenidos.</p><p>En una plataforma educativa no basta con conectar un modelo. Hay que decidir qué datos puede leer, qué límites tendrá y cómo se comprobará que sus respuestas son útiles para el cliente.</p><h2>Diseño responsable</h2><p>Los prompts deben ser claros, los resultados deben revisarse y la interfaz debe explicar cuándo una respuesta ha sido generada automáticamente. También es importante evitar enviar datos personales innecesarios a servicios externos.</p><p>Medir calidad ayuda a mejorar: tiempo ahorrado, satisfacción del usuario, precisión de respuestas y reducción de dudas repetidas.</p><h2>Conclusión</h2><p>La IA bien integrada no sustituye el contenido del curso; lo hace más accesible, guiado y práctico.</p>', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1200&q=82', 2, 'IA', JSON_ARRAY('ia', 'educacion', 'automatizacion'), 9, TRUE, NOW()),
    ('Checklist de ciberseguridad antes de publicar', 'checklist-ciberseguridad-publicar', 'Una lista práctica para revisar autenticación, formularios, permisos, cabeceras, logs y variables antes del despliegue.', '<h2>Seguridad antes del deploy</h2><p>Publicar una aplicación implica revisar más que el diseño. Formularios, sesiones, roles, permisos, cupones y endpoints deben resistir entradas inválidas y accesos no autorizados.</p><p>Un checklist sencillo evita errores frecuentes: validar datos en backend, usar consultas preparadas, proteger tokens, configurar variables de entorno y no mostrar mensajes internos al usuario.</p><h2>Lo que debe comprobarse</h2><p>Las cabeceras de seguridad, el control de CORS, el manejo de errores y los logs son parte de la experiencia profesional. Si algo falla, el sistema debe informar sin exponer detalles sensibles.</p><p>También conviene revisar cuentas demo, contraseñas, rutas de administración y permisos por rol antes de hacer capturas o defensa.</p><h2>Conclusión</h2><p>Una revisión de seguridad convierte el proyecto en un producto más serio y defendible.</p>', 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=1200&q=82', 3, 'Ciberseguridad', JSON_ARRAY('seguridad', 'owasp', 'deploy'), 8, TRUE, NOW()),
    ('Cómo preparar datos para machine learning', 'preparar-datos-machine-learning', 'Antes de entrenar un modelo, los datos deben limpiarse, entenderse y validarse con criterios claros.', '<h2>El modelo empieza en los datos</h2><p>Machine learning no consiste solo en ejecutar una librería. La calidad del resultado depende de cómo se preparan los datos, qué columnas se seleccionan y qué errores se detectan antes de entrenar.</p><p>Valores vacíos, duplicados, escalas distintas y categorías mal codificadas pueden cambiar por completo la predicción. Por eso la exploración inicial es una fase esencial.</p><h2>Proceso recomendado</h2><p>Primero se entiende el objetivo del modelo. Después se limpian datos, se separa entrenamiento y validación, se eligen métricas y se comparan resultados con una línea base simple.</p><p>Documentar ese proceso permite explicar por qué se eligió un modelo y qué limitaciones tiene.</p><h2>Conclusión</h2><p>Preparar bien los datos ahorra tiempo, mejora resultados y hace que un proyecto de IA sea más transparente.</p>', 'https://images.unsplash.com/photo-1555255707-c07966088b7b?auto=format&fit=crop&w=1200&q=82', 2, 'IA', JSON_ARRAY('machine-learning', 'python', 'datos'), 9, TRUE, NOW()),
    ('Testing que sí aporta valor al frontend', 'testing-aporta-valor-frontend', 'Pruebas enfocadas en flujos reales: filtros, formularios, carrito, accesibilidad y estados de error.', '<h2>Probar comportamiento, no implementación</h2><p>Un buen test frontend se parece a lo que haría una persona usuaria: buscar un curso, aplicar un filtro, añadir al carrito o leer un mensaje de error. Eso aporta más valor que comprobar detalles internos frágiles.</p><p>Las pruebas deben cubrir estados críticos: carga, vacío, error, éxito y permisos. Así el equipo detecta fallos antes de que aparezcan en producción.</p><h2>Accesibilidad y confianza</h2><p>React Testing Library anima a buscar elementos por rol, etiqueta o texto visible. Esto favorece componentes más accesibles y más cercanos a la experiencia real.</p><p>Combinado con CI, el testing permite desplegar cambios con menos miedo y explicar mejor la calidad del proyecto.</p><h2>Conclusión</h2><p>Los tests útiles no ralentizan el desarrollo: protegen los flujos que más importan al cliente.</p>', 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=82', 1, 'Testing', JSON_ARRAY('testing', 'frontend', 'calidad'), 7, TRUE, NOW()),
    ('Laravel para APIs mantenibles', 'laravel-apis-mantenibles', 'Estructura rutas, controladores, validaciones, recursos y autenticación para crear backends ordenados.', '<h2>Orden en el backend</h2><p>Laravel ayuda a construir APIs con una estructura clara. Rutas, controladores, modelos y migraciones tienen un lugar definido, lo que facilita entender el proyecto incluso cuando crece.</p><p>Para una plataforma de cursos, esa organización permite separar usuarios, cursos, pedidos, cupones e inscripciones sin mezclar responsabilidades.</p><h2>Buenas prácticas</h2><p>Las validaciones deben vivir en backend, las respuestas JSON deben ser consistentes y los recursos ayudan a decidir qué campos se exponen al frontend. La autenticación y los permisos protegen zonas privadas como el panel de administración.</p><p>Además, las migraciones documentan cómo evoluciona la base de datos.</p><h2>Conclusión</h2><p>Laravel es una buena opción cuando se busca productividad sin renunciar a una arquitectura fácil de mantener.</p>', 'https://images.unsplash.com/photo-1599507593499-a3f7d7d97667?auto=format&fit=crop&w=1200&q=82', 2, 'Backend', JSON_ARRAY('laravel', 'php', 'api'), 8, TRUE, NOW()),
    ('Automatizar builds con GitHub Actions', 'automatizar-builds-github-actions', 'Configura workflows para ejecutar build, tests y despliegues con cada cambio importante del repositorio.', '<h2>Automatización visible</h2><p>GitHub Actions permite convertir tareas repetitivas en workflows. Cada push puede ejecutar instalación de dependencias, build, tests y comprobaciones básicas de calidad.</p><p>Esto aporta confianza al equipo y también mejora la defensa del proyecto: se ve que el repositorio no solo contiene código, sino un proceso de entrega.</p><h2>Qué automatizar primero</h2><p>Lo más útil suele ser empezar por build y tests. Después se pueden añadir lint, auditoría de dependencias, generación de artefactos y despliegue controlado con secrets.</p><p>Un workflow claro debe tener nombres descriptivos, jobs separados y logs fáciles de interpretar.</p><h2>Conclusión</h2><p>Automatizar el pipeline reduce errores manuales y hace que el proyecto parezca más profesional desde la primera captura.</p>', 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?auto=format&fit=crop&w=1200&q=82', 3, 'Automatización', JSON_ARRAY('github-actions', 'ci-cd', 'devops'), 7, TRUE, NOW()) ON DUPLICATE KEY UPDATE title = VALUES(title), excerpt = VALUES(excerpt), content = VALUES(content), cover_image_url = VALUES(cover_image_url), author_id = VALUES(author_id), category = VALUES(category), tags = VALUES(tags), read_time_minutes = VALUES(read_time_minutes), is_published = VALUES(is_published)"
];

$migrationFiles = [
    __DIR__ . '/catalog-quality-update.sql',
    __DIR__ . '/course-reviews-and-counts.sql',
    __DIR__ . '/reset-demo-users.sql',
    __DIR__ . '/more-blog-posts.sql',
    __DIR__ . '/../../database/migrations/2026_05_31_catalog_quality_update.sql',
    __DIR__ . '/../../database/migrations/2026_05_31_course_reviews_and_counts.sql',
    __DIR__ . '/../../database/migrations/2026_05_31_reset_demo_users.sql',
    __DIR__ . '/../../database/migrations/2026_05_31_more_blog_posts.sql',
];

try {
    foreach ($statements as $statement) {
        $conn->exec($statement);
    }
    foreach ($migrationFiles as $migrationFile) {
        if (!is_file($migrationFile)) {
            continue;
        }
        $sql = trim((string) file_get_contents($migrationFile));
        foreach (preg_split('/;\s*(?:\r?\n|$)/', $sql) as $statement) {
            $statement = trim($statement);
            if ($statement !== '') {
                $conn->exec($statement);
            }
        }
    }
    ensureRequiredRoleAccounts($conn);

    sendSuccess(['statements' => count($statements), 'files' => count($migrationFiles)], 'Migración de catálogo, blog y usuarios demo aplicada');
} catch (Throwable $e) {
    if ($conn->inTransaction()) {
        $conn->rollBack();
    }
    sendError('Error al aplicar la migración', 500, $e->getMessage());
}
