UPDATE instructors SET avatar_url = '/instructors/carlos-rodriguez.png' WHERE email = 'carlos@coderup.com';

INSERT INTO courses (id, title, slug, description, thumbnail_url, price, level, category_id, instructor_id, duration_hours, total_lessons, total_students, rating, `requires`, what_you_learn, curriculum, is_published) VALUES
(19, 'Flutter para Apps Multiplataforma', 'flutter-apps-multiplataforma', 'Crea aplicaciones móviles con Flutter y Dart, entendiendo widgets, navegación, formularios, consumo de APIs y publicación. Un curso pensado para construir una app completa con una base mantenible.', 'https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&fit=crop&w=1200&q=82', 49.99, 'Intermedio', 4, 1, 30, 42, 620, 4.70, JSON_ARRAY('Programación básica', 'Conceptos de UI'), JSON_ARRAY('Dart práctico', 'Widgets', 'Navegación', 'Formularios', 'Consumo de APIs', 'Persistencia local', 'Builds', 'Publicación'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Dart y widgets', 'lecciones', JSON_ARRAY('Sintaxis base', 'Stateless y Stateful', 'Layout')), JSON_OBJECT('nombre', 'App conectada', 'lecciones', JSON_ARRAY('HTTP', 'Estados', 'Persistencia')), JSON_OBJECT('nombre', 'Publicación', 'lecciones', JSON_ARRAY('Build Android', 'Build iOS', 'Checklist')))), TRUE),
(20, 'Figma para Sistemas de Diseño', 'figma-sistemas-diseno', 'Organiza interfaces en Figma con componentes, variantes, auto layout, tokens visuales y documentación útil para entregar diseños consistentes a desarrollo.', 'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?auto=format&fit=crop&w=1200&q=82', 34.99, 'Desde cero', 5, 4, 22, 34, 540, 4.60, JSON_ARRAY('Interés por diseño digital', 'Cuenta de Figma'), JSON_ARRAY('Auto layout', 'Componentes', 'Variantes', 'Tokens', 'Prototipos', 'Handoff', 'Accesibilidad visual', 'Documentación'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Base visual', 'lecciones', JSON_ARRAY('Color', 'Tipografía', 'Espaciado')), JSON_OBJECT('nombre', 'Componentes', 'lecciones', JSON_ARRAY('Variantes', 'Estados', 'Librerías')), JSON_OBJECT('nombre', 'Entrega', 'lecciones', JSON_ARRAY('Prototipo', 'Handoff', 'Documentación')))), TRUE),
(21, 'Pentesting Web desde Cero', 'pentesting-web-desde-cero', 'Aprende a detectar vulnerabilidades comunes en aplicaciones web con metodología, laboratorio controlado, reporte técnico y medidas de corrección.', 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=82', 64.99, 'Desde cero', 7, 3, 32, 44, 480, 4.70, JSON_ARRAY('HTTP básico', 'Uso de navegador y terminal'), JSON_ARRAY('Reconocimiento', 'OWASP Top 10', 'Burp Suite básico', 'XSS', 'SQL Injection', 'Control de acceso', 'Reporting', 'Remediación'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Metodología', 'lecciones', JSON_ARRAY('Scope', 'Recon', 'Evidencias')), JSON_OBJECT('nombre', 'Vulnerabilidades', 'lecciones', JSON_ARRAY('XSS', 'SQLi', 'Auth')), JSON_OBJECT('nombre', 'Reporte', 'lecciones', JSON_ARRAY('Riesgo', 'Impacto', 'Corrección')))), TRUE),
(22, 'MLOps para Proyectos con Python', 'mlops-proyectos-python', 'Lleva modelos de machine learning a un flujo reproducible con datasets versionados, pipelines, métricas, empaquetado y despliegue controlado.', 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?auto=format&fit=crop&w=1200&q=82', 69.99, 'Avanzado', 6, 2, 36, 48, 410, 4.70, JSON_ARRAY('Python intermedio', 'Machine learning básico'), JSON_ARRAY('Pipelines', 'Versionado de datos', 'Métricas', 'Experimentos', 'Empaquetado', 'APIs de inferencia', 'Monitorización', 'Reentrenamiento'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Reproducibilidad', 'lecciones', JSON_ARRAY('Entornos', 'Datos', 'Seeds')), JSON_OBJECT('nombre', 'Pipeline ML', 'lecciones', JSON_ARRAY('Entrenamiento', 'Evaluación', 'Registro')), JSON_OBJECT('nombre', 'Servicio', 'lecciones', JSON_ARRAY('API', 'Logs', 'Monitorización')))), TRUE),
(23, 'Kotlin Android Esencial', 'kotlin-android-esencial', 'Construye una app Android moderna con Kotlin, arquitectura por capas, navegación, consumo de APIs y persistencia local.', 'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?auto=format&fit=crop&w=1200&q=82', 44.99, 'Intermedio', 4, 1, 28, 38, 360, 4.60, JSON_ARRAY('Programación básica', 'Conceptos de mobile'), JSON_ARRAY('Kotlin base', 'Activities', 'Compose', 'Navegación', 'HTTP', 'Room', 'Estados', 'Build'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Kotlin y UI', 'lecciones', JSON_ARRAY('Sintaxis', 'Compose', 'Estados')), JSON_OBJECT('nombre', 'Datos', 'lecciones', JSON_ARRAY('API', 'Room', 'Repositorios')), JSON_OBJECT('nombre', 'Entrega', 'lecciones', JSON_ARRAY('Build', 'Testing', 'Release')))), TRUE),
(24, 'Arquitectura Cloud en AWS', 'arquitectura-cloud-aws', 'Diseña despliegues en AWS con redes, cómputo, almacenamiento, bases de datos gestionadas, seguridad básica y control de costes.', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=82', 59.99, 'Intermedio', 3, 3, 34, 46, 520, 4.80, JSON_ARRAY('Linux básico', 'Conceptos de redes'), JSON_ARRAY('VPC', 'EC2', 'S3', 'RDS', 'IAM', 'Load balancing', 'Costes', 'Arquitectura'), JSON_OBJECT('modulos', JSON_ARRAY(JSON_OBJECT('nombre', 'Fundamentos cloud', 'lecciones', JSON_ARRAY('Regiones', 'IAM', 'VPC')), JSON_OBJECT('nombre', 'Servicios base', 'lecciones', JSON_ARRAY('EC2', 'S3', 'RDS')), JSON_OBJECT('nombre', 'Diseño', 'lecciones', JSON_ARRAY('Alta disponibilidad', 'Seguridad', 'Costes')))), TRUE)
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  description = VALUES(description),
  thumbnail_url = VALUES(thumbnail_url),
  price = VALUES(price),
  level = VALUES(level),
  category_id = VALUES(category_id),
  instructor_id = VALUES(instructor_id),
  duration_hours = VALUES(duration_hours),
  total_lessons = VALUES(total_lessons),
  `requires` = VALUES(`requires`),
  what_you_learn = VALUES(what_you_learn),
  curriculum = VALUES(curriculum),
  is_published = VALUES(is_published);

UPDATE posts SET read_time_minutes = GREATEST(1, CEIL(LENGTH(content) / 1200)) WHERE is_published = 1;

UPDATE posts
SET content = CONCAT(
  content,
  '<h2>Cómo llevarlo a la práctica</h2><p>Para que la lectura no se quede en teoría, conviene convertir cada idea en una comprobación pequeña dentro de un proyecto. Primero identifica el problema técnico que resuelve el artículo: estado, diseño, seguridad, datos, despliegue o mantenimiento. Después crea un ejemplo mínimo donde puedas ver el comportamiento antes y después del cambio.</p><p>Una buena práctica es escribir una lista corta de criterios observables. Por ejemplo: qué entrada acepta el sistema, qué respuesta debe mostrar, qué error debe evitar y cómo se confirma que el resultado funciona. Esta forma de trabajar ayuda a que el aprendizaje sea medible y evita copiar código sin entenderlo.</p><p>También es útil guardar notas de decisión. Explica por qué elegiste una solución, qué alternativa descartaste y qué limitaciones quedan pendientes. Esa documentación convierte un ejercicio en material de portfolio y facilita volver al proyecto semanas después sin perder contexto.</p><h2>Checklist de revisión</h2><p>Antes de cerrar el tema, revisa que el código sea legible, que los nombres expliquen intención, que los estados de error estén contemplados y que la interfaz mantenga contraste suficiente. Si hay datos externos, comprueba carga, vacío y fallo. Si hay despliegue, revisa variables de entorno, logs y rutas públicas.</p><p>El objetivo no es memorizar todas las herramientas, sino desarrollar criterio para aplicar cada técnica en el lugar adecuado. Cuando puedas explicar el problema, la solución y la forma de verificarla, la lectura ya se ha transformado en aprendizaje práctico.</p>'
)
WHERE is_published = 1
  AND content NOT LIKE '%Cómo llevarlo a la práctica%';

UPDATE posts SET read_time_minutes = GREATEST(2, CEIL(LENGTH(content) / 1200)) WHERE is_published = 1;
